---
kind: pipeline
type: docker
name: default

steps:
  - name: web
    image: node:current
    commands:
      - npm --prefix web install
      - npm --prefix web run build
  - name: server
    image: hanfer/xgo-libusb:latest
    environment:
      GITHUB_TOKEN:
        from_secret: config_github_token
    commands:
      - /run-env.sh linux make linux
      - /run-env.sh windows make windows
      - /run-env.sh darwin make darwin
  - name: publish-github
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: quic-config*.zip
      prerelease: true
      title: latest
      overwrite: true
    when:
      event:
        - tag
  - name: publish-hanfer
    image: appleboy/drone-scp
    settings:
      host: hanfer.org
      user: drone
      password:
        from_secret: ssh_password
      source: quic-config*.zip
      target: /mnt/hanfer/public
