---
kind: pipeline
type: docker
name: default

steps:
  - name: web
    image: node:current
    commands:
      - npm --prefix web install
      - npm --prefix web run build
  - name: server
    image: golang:latest
    commands:
      - make all
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: usb_configurator_*.zip
      prerelease: true
      title: latest
      overwrite: true
    when:
      event:
        - tag
