---
kind: pipeline
type: docker
name: default

steps:
  - name: web
    image: hanfer/node-wine:14
    commands:
      - npm install
      - npm run build
  - name: publish-github
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - build/quic-config*.zip
        - build/quic-config*.exe
    when:
      event:
        - tag
