name: build-develop
on:
  push:
    branches:
      - "develop"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Test Pages publishing
        run: node --test script/pages.test.mjs

      - name: cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-develop-node_modules

      - name: install npm packages
        run: npm install

      - name: build gh-pages
        run: |
          npm run build:gh-pages

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gh-pages
          path: docs
