name: build
on:
  push:
    branches:
      - 'master'
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hanfer/node-wine:16
      options: --cpus 2
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules

      - name: install npm packages
        run: npm install

      - name: build standalone
        if: startsWith(github.ref, 'refs/tags/')
        run: npm run build

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/quic-config*.zip
            build/quic-config*.exe

      - name: build gh-pages
        run: |
          npm run build:gh-pages
          echo 'config.bosshobby.com' > docs/CNAME

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gh-pages
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: checkout gh-pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git checkout gh-pages

      - uses: actions/download-artifact@v3
        with:
          name: gh-pages

      - name: update gh-pages
        run: |
          git add .
          git commit -m "GitHub Pages $GITHUB_SHA" || exit 0
          git remote set-url --push origin https://actions:$GITHUB_TOKEN@github.com/BossHobby/Configurator
          git push -f
